# chapter: R Basics
```{r,eval=FALSE}
install.packages(c("ggplot2", "gcookbook"))
library(ggplot2)
library(gcookbook)
```
## 1.1.Installing a Package 
```{r,eval=FALSE}
install.packages("ggplot2")
```
    
## 1.2.Loading a Package 
```{r}
library(ggplot2)
```
## 1.3.Loading a Delimited Text Data File
```{r}
data <- read.csv("datafile.csv")
data <- read.csv("datafile.csv", header=FALSE)
    
# Manually assign the header names
names(data) <- c("Column1","Column2","Column3")
    
data <- read.csv("datafile.csv", sep="\t")
    
data <- read.csv("datafile.csv", stringsAsFactors=FALSE)

# Convert to factor
data$Sex <- factor(data$Sex)

str(data)
```

## 1.4.Loading Data from an Excel File
```{r,eval=FALSE}
# Only need to install once
install.packages("xlsx")

library(xslx)
data <- read.xlsx("datafile.xlsx", 1)
    
# Only need to install once
install.packages("gdata")

library(gdata)
# Read first sheet
data <- read.xls("datafile.xls")
    
    
data <- read.xlsx("datafile.xls", sheetIndex=2)

data <- read.xlsx("datafile.xls", sheetName="Revenues")
    
    
data <- read.xls("datafile.xls", sheet=2)
```
## 1.5.Loading Data from an SPSS File
```{r,eval=FALSE}
# Only need to install the first time
install.packages("foreign")

library(foreign)
data <- read.spss("datafile.sav")
